server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: pago-service
              uri: lb://metodo-de-pago
              predicates:
                - Path=/api/v1/boletas/**

            - id: carrito-service
              uri: lb://carrito-compras
              predicates:
                - Path=/api/v1/Carrito/**

            - id: cliente-service
              uri: lb://cliente
              predicates:
                - Path=/api/clientes/**

            - id: inventario-service
              uri: lb://inventario
              predicates:
                - Path=/api/products/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/