version: '3.8'

services:
  db_cliente_proyecto:
    image: mysql:8.4
    container_name: db_cliente_proyecto
    environment:
      MYSQL_DATABASE: db_cliente_proyecto
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  cliente-service:
    build: .
    container_name: cliente_service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db_carrito:3306/db_cliente_proyecto
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      db_cliente_proyecto:
        condition: service_healthy