spring.datasource.url=jdbc:mysql://localhost:3306/db_cliente_proyecto_test?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
Spring.jpa.properties.hibernate.format_sql=true


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

microservicio.carrito.url=http://localhost:8083/api/v1/Carrito
microservicio.pago.url=http://localhost:8084/api/v1/boletas
microservicio.inventario.url=http://localhost:8081/api/products