spring.datasource.url=jdbc:mysql://localhost:3306/db_cliente_proyecto_dev
spring.datasource.username=root
spring.datasource.password=
server.port:8082

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
Spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

microservicio.carrito.url=http://localhost:8083/api/v1/Carrito
microservicio.pago.url=http://localhost:8084/api/v1/boletas
microservicio.inventario.url=http://localhost:8081/api/products