spring.datasource.url=jdbc:mysql://localhost:3306/db_inventario_proyecto_test
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
Spring.jpa.properties.hibernate.format_sql=true


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html